from typing import Any

SCENARIO_REGISTRY: list[dict[str, Any]] = [
    {
        "id": "RACE-001",
        "name": "Synthetic Balance Overdraft Race",
        "description": "Multiple concurrent withdrawal requests read the same available balance before any write is committed. The check-then-act pattern allows more withdrawals than the balance supports.",
        "category": "gift-card-balance",
        "difficulty": "beginner",
        "sharedState": "account_balance",
        "invariant": {
            "type": "minimum_balance",
            "description": "Account balance must never fall below zero",
            "constraint": {"minimum": 0, "field": "balance"},
        },
        "fixture": {
            "id": "fix-balance-vuln-v1",
            "name": "Balance Check-Then-Act",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Reads balance, checks sufficiency, then writes without holding a lock. The race window spans the delay between read and write.",
        },
        "hardenedFixture": {
            "id": "fix-balance-hard-v1",
            "name": "Atomic Balance Update",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "asyncio.Lock wraps the read-check-write sequence atomically.",
            "mitigationType": "atomic-update",
            "mitigationDescription": "asyncio.Lock prevents concurrent execution of the critical section.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "local-lab",
        "tags": ["balance", "check-then-act", "asyncio", "python"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-002",
        "name": "Coupon Single-Use Bypass",
        "description": "A one-use coupon can be redeemed multiple times if concurrent requests pass the 'already used?' check simultaneously.",
        "category": "coupon-redemption",
        "difficulty": "beginner",
        "sharedState": "coupon_used_flag",
        "invariant": {
            "type": "single_use",
            "description": "Coupon must not be redeemed more than once",
            "constraint": {"maximum": 1, "field": "used_count"},
        },
        "fixture": {
            "id": "fix-coupon-vuln-v1",
            "name": "Coupon Check-Then-Redeem",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Reads used flag, checks if unused, then marks used — without atomicity.",
        },
        "hardenedFixture": {
            "id": "fix-coupon-hard-v1",
            "name": "Atomic Coupon Redemption",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Uses database UNIQUE constraint and INSERT to ensure atomic single redemption.",
            "mitigationType": "database-constraint",
            "mitigationDescription": "UNIQUE constraint on coupon_redemptions table prevents duplicate rows.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "demo",
        "tags": ["coupon", "single-use", "check-then-act"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-003",
        "name": "Inventory Overselling Race",
        "description": "Last-unit inventory can be sold multiple times when concurrent purchase requests both observe stock > 0 before either decrements it.",
        "category": "inventory-update",
        "difficulty": "intermediate",
        "sharedState": "product_inventory",
        "invariant": {
            "type": "non_negative",
            "description": "Inventory count must not fall below zero",
            "constraint": {"minimum": 0, "field": "inventory"},
        },
        "fixture": {
            "id": "fix-inventory-vuln-v1",
            "name": "Inventory Check-Then-Decrement",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Reads inventory count, checks availability, then decrements — without atomicity.",
        },
        "hardenedFixture": {
            "id": "fix-inventory-hard-v1",
            "name": "Atomic Inventory Decrement",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Uses UPDATE inventory SET count = count - 1 WHERE count > 0.",
            "mitigationType": "atomic-update",
            "mitigationDescription": "Conditional atomic UPDATE — returns 0 rows if already depleted.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "demo",
        "tags": ["inventory", "oversell", "e-commerce"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-004",
        "name": "Account Registration Duplicate",
        "description": "Two concurrent registrations with the same username can both pass the uniqueness check before either creates the record.",
        "category": "account-registration",
        "difficulty": "intermediate",
        "sharedState": "user_registry",
        "invariant": {
            "type": "unique_account",
            "description": "Each username must correspond to exactly one account",
            "constraint": {"field": "duplicate_count"},
        },
        "fixture": {
            "id": "fix-reg-vuln-v1",
            "name": "Registration Check-Then-Insert",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "SELECT then INSERT without atomic check — two requests can both pass the SELECT check.",
        },
        "hardenedFixture": {
            "id": "fix-reg-hard-v1",
            "name": "Unique Constraint Registration",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "INSERT with UNIQUE constraint on username — database atomically enforces uniqueness.",
            "mitigationType": "database-constraint",
            "mitigationDescription": "UNIQUE constraint on username column; IntegrityError caught and mapped to 409 Conflict.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "local-lab",
        "tags": ["registration", "duplicate", "database", "constraint"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-005",
        "name": "Database TOCTOU Balance Check",
        "description": "Demonstrates the TOCTOU pattern at the database layer: SELECT then UPDATE without row-level locking.",
        "category": "database-toctou",
        "difficulty": "intermediate",
        "sharedState": "db_account_balance",
        "invariant": {
            "type": "minimum_balance",
            "description": "Database balance must never go below zero",
            "constraint": {"minimum": 0, "field": "balance"},
        },
        "fixture": {
            "id": "fix-dbtoctou-vuln-v1",
            "name": "Unprotected SELECT-UPDATE",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Plain SELECT then UPDATE — no transaction isolation prevents concurrent reads of the same value.",
        },
        "hardenedFixture": {
            "id": "fix-dbtoctou-hard-v1",
            "name": "Atomic Conditional UPDATE",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Single UPDATE with WHERE balance >= withdrawal — no separate SELECT needed.",
            "mitigationType": "atomic-update",
            "mitigationDescription": "Database atomically evaluates and applies the conditional update.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "local-lab",
        "tags": ["database", "toctou", "sqlite", "transaction"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-006",
        "name": "Filesystem Exclusive Claim Race",
        "description": "Two processes race to claim a file resource. The check-then-create pattern allows both to observe absence and then attempt creation.",
        "category": "filesystem-toctou",
        "difficulty": "intermediate",
        "sharedState": "filesystem_claim_file",
        "invariant": {
            "type": "single_use",
            "description": "Only one process may claim the resource file",
            "constraint": {"maximum": 1, "field": "claim_count"},
        },
        "fixture": {
            "id": "fix-fs-vuln-v1",
            "name": "os.path.exists() + open()",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Checks existence with os.path.exists() then opens for writing — race between check and create.",
        },
        "hardenedFixture": {
            "id": "fix-fs-hard-v1",
            "name": "O_CREAT | O_EXCL Atomic Creation",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Uses os.open() with O_CREAT | O_EXCL — atomically fails if file already exists.",
            "mitigationType": "atomic-file-creation",
            "mitigationDescription": "O_CREAT | O_EXCL is atomic at the kernel level — only one opener succeeds.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "local-lab",
        "tags": ["filesystem", "toctou", "o_excl", "file-locking"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-007",
        "name": "Rate Limit Counter Overflow",
        "description": "A per-user rate limit counter implemented as read-increment-write allows more requests than permitted when concurrent increments race.",
        "category": "rate-limit-counter",
        "difficulty": "advanced",
        "sharedState": "rate_limit_counter",
        "invariant": {
            "type": "max_count",
            "description": "Request count must not exceed configured rate limit",
            "constraint": {"maximum": 5, "field": "request_count"},
        },
        "fixture": {
            "id": "fix-ratelimit-vuln-v1",
            "name": "Non-Atomic Rate Counter",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Reads counter, checks limit, then increments — concurrent reads see the same value.",
        },
        "hardenedFixture": {
            "id": "fix-ratelimit-hard-v1",
            "name": "Atomic Rate Counter",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Uses atomic compare-and-swap or database atomic increment with limit check.",
            "mitigationType": "compare-and-set",
            "mitigationDescription": "Atomic increment ensures each worker's update is serialized.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "demo",
        "tags": ["rate-limit", "counter", "overflow"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-008",
        "name": "Queue Job Duplicate Claim",
        "description": "Multiple workers race to claim the same queued job, resulting in duplicate processing when the claim check is not atomic.",
        "category": "queue-job-claim",
        "difficulty": "advanced",
        "sharedState": "job_queue",
        "invariant": {
            "type": "single_use",
            "description": "Each job must be claimed by exactly one worker",
            "constraint": {"maximum": 1, "field": "claim_count"},
        },
        "fixture": {
            "id": "fix-queue-vuln-v1",
            "name": "Non-Atomic Job Claim",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "SELECT available job then UPDATE claimed — two workers can both select before either updates.",
        },
        "hardenedFixture": {
            "id": "fix-queue-hard-v1",
            "name": "Atomic Job Claim with SKIP LOCKED",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Atomic UPDATE claiming the job with a WHERE status = unclaimed condition.",
            "mitigationType": "pessimistic-locking",
            "mitigationDescription": "Atomic UPDATE returns 0 rows if already claimed — workers see a definitive result.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "demo",
        "tags": ["queue", "job-worker", "duplicate-processing"],
        "status": "available",
        "evidenceAvailable": True,
    },
    {
        "id": "RACE-009",
        "name": "Session Token Issuance Race",
        "description": "Concurrent login requests for the same user can each create a separate session token, violating a single-session-per-user policy.",
        "category": "session-issuance",
        "difficulty": "advanced",
        "sharedState": "session_store",
        "invariant": {
            "type": "single_use",
            "description": "At most one active session per user account",
            "constraint": {"maximum": 1, "field": "session_count"},
        },
        "fixture": {
            "id": "fix-session-vuln-v1",
            "name": "Non-Atomic Session Creation",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "Checks for existing session then inserts — both requests can pass the check simultaneously.",
        },
        "hardenedFixture": {
            "id": "fix-session-hard-v1",
            "name": "Idempotent Session Issuance",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "INSERT OR REPLACE with unique constraint on user_id — subsequent inserts update the existing record.",
            "mitigationType": "idempotency-key",
            "mitigationDescription": "UNIQUE constraint on user_id prevents duplicate sessions at the database level.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "demo",
        "tags": ["session", "authentication", "idempotency"],
        "status": "available",
        "evidenceAvailable": False,
    },
    {
        "id": "RACE-010",
        "name": "Distributed Counter Race",
        "description": "Two application workers share a counter in a distributed store. Non-atomic read-modify-write creates a lost-update race.",
        "category": "distributed-state",
        "difficulty": "expert",
        "sharedState": "distributed_counter",
        "invariant": {
            "type": "max_count",
            "description": "Distributed counter must reflect all increments",
            "constraint": {"field": "counter_value"},
        },
        "fixture": {
            "id": "fix-dist-vuln-v1",
            "name": "Non-Atomic Distributed Increment",
            "version": "1.0.0",
            "mode": "vulnerable",
            "language": "python",
            "description": "GET + SET across two workers without atomicity — concurrent GETs return same value.",
        },
        "hardenedFixture": {
            "id": "fix-dist-hard-v1",
            "name": "Atomic Distributed Increment",
            "version": "1.0.0",
            "mode": "hardened",
            "language": "python",
            "description": "Uses atomic INCR operation or optimistic locking with version check.",
            "mitigationType": "compare-and-set",
            "mitigationDescription": "Atomic increment ensures each worker's update is serialized.",
        },
        "expectedVulnerableResult": "violated",
        "expectedHardenedResult": "preserved",
        "executionMode": "demo",
        "tags": ["distributed", "counter", "lost-update"],
        "status": "available",
        "evidenceAvailable": True,
    },
]
